/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Config
         * @description Allowed providers/models and defaults from server config (for UI dropdowns).
         */
        get: operations["llm_config_config_llm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Config */
        get: operations["runtime_config_config_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sessions Off Create */
        post: operations["_sessions_off_create_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions Off Get */
        get: operations["_sessions_off_get_sessions__sid__get"];
        put?: never;
        post?: never;
        /** Sessions Off Delete */
        delete: operations["_sessions_off_delete_sessions__sid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sid}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sessions Off Documents */
        post: operations["_sessions_off_documents_sessions__sid__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Stream */
        post: operations["query_stream_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observability/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observability Dashboard
         * @description Return real-time observability metrics for dashboarding.
         */
        get: operations["observability_dashboard_observability_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CitationModel */
        CitationModel: {
            /** Raw Id */
            raw_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Resolved */
            resolved: boolean;
            /** Title */
            title?: string | null;
            /** Filename */
            filename?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Section Title */
            section_title?: string | null;
            /** Source */
            source?: string | null;
            /** Evidence Anchor */
            evidence_anchor?: string | null;
            /** Claim Text */
            claim_text?: string | null;
            /** Text Preview */
            text_preview?: string | null;
            /**
             * Verification Score
             * @default 0
             */
            verification_score: number;
            /**
             * Verification
             * @default unresolved
             */
            verification: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthModel */
        HealthModel: {
            /** Status */
            status: string;
            /** Collection */
            collection: string;
        };
        /**
         * LLMConfigModel
         * @description Public LLM routing options for UI clients (no secrets).
         */
        LLMConfigModel: {
            /** Default Provider */
            default_provider: string;
            /** Default Model By Provider */
            default_model_by_provider: {
                [key: string]: string;
            };
            /** Allowed Models By Provider */
            allowed_models_by_provider: {
                [key: string]: string[];
            };
            /**
             * Provider Key Configured
             * @description Whether server-side API key env vars are configured for each provider
             */
            provider_key_configured?: {
                [key: string]: boolean;
            };
            /**
             * Demo Mode
             * @description True when API is running in hosted demo profile
             * @default false
             */
            demo_mode: boolean;
        };
        /** MetricsModel */
        MetricsModel: {
            /** Cache Ttl Seconds */
            cache_ttl_seconds: number;
            /** Available Providers */
            available_providers: string[];
        };
        /** QueryRequestModel */
        QueryRequestModel: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Use Llm
             * @default true
             */
            use_llm: boolean;
            /**
             * Use Rerank
             * @default true
             */
            use_rerank: boolean;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /**
             * Include Citations
             * @default true
             */
            include_citations: boolean;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Reranker Model */
            reranker_model?: string | null;
            /** Provider Api Key */
            provider_api_key?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Knowledge Scope
             * @default global
             * @enum {string}
             */
            knowledge_scope: "global" | "session" | "both";
            /** Embedding Profile */
            embedding_profile?: string | null;
            /**
             * Retrieval Mode
             * @default hybrid
             * @enum {string}
             */
            retrieval_mode: "bm25" | "vector" | "hybrid";
        };
        /** QueryResponseModel */
        QueryResponseModel: {
            /** Query */
            query: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * Processing Time Ms
             * @default 0
             */
            processing_time_ms: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Validation Issues */
            validation_issues?: string[];
            /** Citations */
            citations?: components["schemas"]["CitationModel"][];
            /** Retrieved */
            retrieved?: components["schemas"]["RetrievedChunkModel"][];
            truthfulness?: components["schemas"]["TruthfulnessModel"] | null;
            /** Embedding Profile */
            embedding_profile?: string | null;
            /**
             * Status
             * @default answered
             */
            status: string;
            /** Refusal Reason */
            refusal_reason?: string | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
        };
        /** RetrievedChunkModel */
        RetrievedChunkModel: {
            /** Id */
            id: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Source
             * @default hybrid
             */
            source: string;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Preview
             * @default
             */
            preview: string;
            /** Cross Encoder Score */
            cross_encoder_score?: number | null;
            /** Rerank Position */
            rerank_position?: number | null;
        };
        /** RuntimeConfigModel */
        RuntimeConfigModel: {
            /** Chunking Default Strategy */
            chunking_default_strategy: string;
            /** Chunking Allowed Strategies */
            chunking_allowed_strategies: string[];
            /** Embedding Default Profile */
            embedding_default_profile: string;
            /** Embedding Profiles */
            embedding_profiles: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** TruthfulnessModel */
        TruthfulnessModel: {
            /**
             * Nli Faithfulness
             * @default 0
             */
            nli_faithfulness: number;
            /**
             * Citation Groundedness
             * @default 0
             */
            citation_groundedness: number;
            /**
             * Uncited Claims
             * @default 0
             */
            uncited_claims: number;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type CitationModel = components['schemas']['CitationModel'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type HealthModel = components['schemas']['HealthModel'];
export type LlmConfigModel = components['schemas']['LLMConfigModel'];
export type MetricsModel = components['schemas']['MetricsModel'];
export type QueryRequestModel = components['schemas']['QueryRequestModel'];
export type QueryResponseModel = components['schemas']['QueryResponseModel'];
export type RetrievedChunkModel = components['schemas']['RetrievedChunkModel'];
export type RuntimeConfigModel = components['schemas']['RuntimeConfigModel'];
export type TruthfulnessModel = components['schemas']['TruthfulnessModel'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthModel"];
                };
            };
        };
    };
    llm_config_config_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigModel"];
                };
            };
        };
    };
    runtime_config_config_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfigModel"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _sessions_off_create_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    _sessions_off_get_sessions__sid__get: {
        parameters: {
            query: {
                _sid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _sessions_off_delete_sessions__sid__delete: {
        parameters: {
            query: {
                _sid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _sessions_off_documents_sessions__sid__documents_post: {
        parameters: {
            query: {
                _sid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_stream_query_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observability_dashboard_observability_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
